name: Fly Deploy
on: 
  workflow_dispatch:
   inputs:
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true 

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    steps:
      - uses: actions/checkout@v2
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: |
          flyctl secrets set UUID="${UUID}"
          flyctl regions set ${REGION}
          flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          APP_NAME: ${{ secrets.APP_NAME }}
          UUID: ${{ secrets.UUID }}

