name: Fly Deploy
on: 
  workflow_dispatch:
   inputs:
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true 
  push:
  schedule:
    - cron: '0 4 1 * *'

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy
        run: |
          sh ./deploy.sh
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          APP_NAME: ${{ secrets.APP_NAME }}
          UUID: ${{ secrets.UUID }}
          ENVIRONMENT: ${{ github.event.inputs.environment }}
